Move RTCRtpEncodingParameters.codec to main spec
w3c/webrtc-extensions pull request #219
Opened 2024-08-19 10:02 UTC by dontcallmedom

close #212
parallel to w3c/webrtc-pc#2985

2024-08-19 13:12 UTC, Orphis commented
You also need to remove modifications to setParameters, addTransceiver and negotiation procedure that relate to it.

2024-08-19 14:20 UTC, jan-ivar requested changes

2024-08-19 14:20 UTC, jan-ivar commented on index.html
> -        </dd>
There's more to https://github.com/w3c/webrtc-extensions/pull/147 that needs to be moved I think.

2024-08-22 11:55 UTC, Orphis approved these changes

2024-08-22 14:14 UTC, youennf approved these changes

2024-08-22 14:15 UTC, merged