Add a requestKeyframe() API
w3c/webrtc-extensions pull request #37
Opened 2020-05-12 13:51 UTC by alvestrand

This was the simplest API I could think of.
The use of the operations chain (which I haven't been able to cite correctly) is to make it not racy with replaceTrack(), which is also on the operations chain.

I'd like to have comments from hbos and jib before proposing this to the WG.

2020-05-12 13:55 UTC, murillo128 commented
I like the API!

How does it behave with simulcast and SVC (K-SVC)? Can an key frame be requested for particular layer/stream (like the RTCP LRR)?

2020-05-12 14:09 UTC, alvestrand commented
Good question. I think it needs a layer argument (with default being "all layers").

2020-05-12 14:15 UTC, alvestrand commented
@aboba is there a way in some SVC spec to refer consistently to a specific layer?
Does the question even make sense?
For simulcast, indexing the layers in Encodings should be sufficient.

2020-05-12 20:30 UTC, fippo commented
@alvestrand related to e2ee stuff?
Please note the opinion of the google team on PLIs/keyframes in relation to simulcast and per-stream keyframes, see https://bugs.chromium.org/p/webrtc/issues/detail?id=10107 (also :wave: @ibc)

IIRC a SRD/SLD also triggers a keyframe (or rather: encoder reset)

2020-05-12 20:39 UTC, ibc commented
What is this API needed for?

2020-05-12 22:55 UTC, aboba commented
@alvestrand The [FIR message](https://tools.ietf.org/html/rfc5104#section-4.3.1.1) utilizes SSRC(s) to indicate the target(s) of the request. So the FIR is assumed to apply to all layers on the target SSRC, [as well as associated SSRCs in the case of layered codecs](https://tools.ietf.org/html/rfc8082#section-4). The [LRR](https://tools.ietf.org/html/draft-ietf-avtext-lrr) utilizes an SSRC, but also includes other fields such TTID (the target temporal layer), TLID (the target spatial layer), etc.

Note the updated definition of "decoder refresh point" in [RFC 8082](https://tools.ietf.org/html/rfc8082#page-4).

2020-05-12 23:36 UTC, aboba commented
@murillo128 How it behaves will depend on what message gets generated as a result (FIR or LRR). For an FIR, the encoder(s) associated with the target SSRCs will generate a refresh point. If a single encoder is generating simulcast, this can result in **all** of the simulcast streams generating a key frame, as described [here.](https://aomediacodec.github.io/av1-rtp-spec/#81--full-intra-request-fir). LRR behavior is described [here. ](https://aomediacodec.github.io/av1-rtp-spec/#82--layer-refresh-request-lrr)

2020-05-14 08:44 UTC, youennf commented
It would be good to understand the use case.
For instance, would applications like to control the maximum time between key frames an encoder uses, with two extreme cases being key frame only and no key frame except in case of FIR?

A few additional questions:
- Would it also be useful for some audio codecs?
- Is it WebRTC specific or is there a use case for MediaRecorder as well?
- What does it mean for muted content? I guess the next frame would be a key frame, which might require waiting for 1 sec, so the promise would resolve after 1 sec. Is it correct?
- What should be the behaviour if this method is called 10 times synchronously? Should there be one key frame or should the next 10 frames be key frames?
- Is it an issue to be able to compute how long it will take to generate a key frame (say I call this API on a canvas track and after some time, I generate a canvas frame and compute the time between the canvas frame generation and the promise resolution)?
- This is using the operation chain, probably to keep consistency with the replaceTrack trick. Is that so? Is there any other reason? Is there a future need to control exactly which frame would get encoded as a key frame?

2020-05-14 08:53 UTC, alvestrand commented on index.html
> +                Let <var>connection</var> be the sender''s associated
delete double quote

2020-05-14 14:35 UTC, alvestrand commented
@youennf the use case that came up this time is to make sure a keyframe is sent each time you change the encryption key on a group call.

Perhaps this is better called "produceKeyframe"?

2020-05-14 14:36 UTC, aboba commented
Didn't realize this was for the sender, not the receiver.  So it's not really a request, it's more like "generateKeyFrame".

2020-05-14 16:14 UTC, youennf commented
I see, so it might make sense for audio if codecs use some prediction. Maybe the promise should not reject then?

An alternative solution is for the e2e JS transform module to state that it needs a key frame as part of the additional frame metadata given to the packetizer for each processed frame. That might be also useful for a non JS e2e module for which the key changes might not be visible to the script.

2020-05-14 16:16 UTC, ibc commented
Let me insist, please. What is this API needed for? And if the answer is e2ee, why?

2020-05-14 16:27 UTC, murillo128 commented
the e2ee key is exchanged in a different path than sfu signaling, so it may
be updated on the sender shortly after the new participant has joined and
the sfu jas already requested the key frame.

Updating the key on a key frame makes a lot of sense to me.

Anyway, I am always in favor of more APIs that allow lower level control of
the underlaying objects.

Do you foresee any way this API could cause any issue to existing code?

El jue., 14 may. 2020 18:17, Iñaki Baz Castillo <notifications@github.com>
escribió:

> Let me insist, please. What is this API needed for? And if the answer is
> e2ee, why?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/w3c/webrtc-extensions/pull/37#issuecomment-628739263>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAIFN43V35GF5LLGQSVQW43RRQKQDANCNFSM4M63A53A>
> .
>

2020-05-14 16:30 UTC, ibc commented
> Do you foresee any way this API could cause any issue to existing code?

No, but neither I can figure out how your response explains what this API is needed for :)

2020-05-14 17:17 UTC, murillo128 commented
Forward and Post-Compromise Security requires that the e2ee keys are updated anytime a participant joins/leave the call.
https://tools.ietf.org/html/draft-ietf-mls-architecture-04#section-3.2.2.1

The key exchange happens async and on a different path than the webrtc signaling and media (by definition). So it may happen that when a new participant joins the SFU side request a key frame and the sender generates the e2ee encrypted frame with a key not known by the receiver, so it will be discarded. When the sender updates his sending key with the new key, it will send it in a non-key frame frame, so the receiver will be able to decrypt it, but not decode it.

Receiver will re-request an key frame then, but due to sender and sfu policies, that new key frame could take some time to be generated.

It the sender sends a key frame when the new e2ee key is in use, the time required for the new participant to display the video is minimized.

Also, there are several optimizations (specially on authenticating and signing) that can be done on key frames, so it is always interesting to be able to control the key frame generation from the e2ee side.

Hope it is clearer now.

2020-05-14 18:24 UTC, fippo commented on index.html
> +  <section id="recrtpsender-interface">
s/rectpsender/rtpsender/

2020-05-14 18:25 UTC, fippo commented on index.html
> +                If the sender''s track is not set, if the track is ended,
delete double quote

2020-05-14 18:32 UTC, fippo commented
In particular in the context of insertable streams I don't care about when the next keyframe happens, no? I could request one to be generated and would rotate the key at the next keyframe that the transform sees. Now if there are two changes to the e2ee key in rapid succession... then what?

I don't think resolving with a single timestamp works for simulcast where we have three different timestamp sequences.

2020-05-14 18:39 UTC, fippo commented
> Didn't realize this was for the sender, not the receiver. So it's not really a request, it's more like "generateKeyFrame".

Do we need a requestKeyFrame on the receiver? Mainly to handle decrypt errors.

2020-05-15 10:09 UTC, youennf commented
Given the use case, this API might better fit with insertable streams.
To reduce race issues, this API should be tied as close as possible to the encoder, the ReadableStream being the closest we have.

> Do we need a requestKeyFrame on the receiver? Mainly to handle decrypt errors.

Seems to make sense, for metadata as well in theory. That is a bit more tricky since this API is trying to influence the encoder of the other side, communication channel being potentially lossy.

2021-03-05 13:30 UTC, youennf commented
@alverstrand, given the usecase is insertable streams, should we move this issue to webrtc-insertable-streams repo?

2021-03-22 11:53 UTC, solmaks commented
@alvestrand , I think we should resurrect this work. RTCRtpSender::replaceTrack workaround is not working reliably (seems like a race), and other workarounds (e.g. scaleResolutionBy toggle) are fundamentally flawed too. It seems that time is right for adding a first party API to request key frames on sender.

2021-03-22 12:43 UTC, youennf commented
@solmaks, can you share your usecase? Is it tied to using webrtc encoded transforms?
Safari has experimental support for this requestKeyFrame API as part of its insertable streams API experiment (in RTCRtpScriptTransformer) since there are known use cases there.
Using an identity transform just for getting access to this API would be cumbersome and might prove that this is not the right place (or only place) for such an API.

2021-03-22 21:02 UTC, solmaks commented
Actually it is not. Scenario is dead simple - adjust send stream bitrate and trigger key frame right after. We do have a mechanism for adjusting bitrate of individual encodings, per encoding key frame triggering is missing fully. It would be great if we could avoid bundling KF API with insertable streams or any other mechanisms involving heavy per-packet processing, as the latter has impact on power and performance.

2021-03-23 09:08 UTC, youennf commented
> adjust send stream bitrate and trigger key frame right after.

I see. In the case of simulcast, you would like to trigger a key frame for one encoding but not the others.
The closest API surface we have here is RTCRtpSendParameters.encodings.
I would have hoped that, when we go from active=false to active=true, video encoders would start with a key frame.
Maybe this is something we could agree on.

> It would be great if we could avoid bundling KF API with insertable streams or any other mechanisms involving heavy per-packet processing, as the latter has impact on power and performance.

I agree it would be cumbersome to use, not sure about power impact if frames are not mutated. Cost might be reduced to two thread hops.

2021-03-23 11:12 UTC, solmaks commented
> I see. In the case of simulcast, you would like to trigger a key frame for one encoding but not the others.
> The closest API surface we have here is RTCRtpSendParameters.encodings.

Yes, this is what I was thinking of as well. This new parameter might need a special treatment though, as it is transient in nature. I.e. configuring it on an encoding and reading it back would not make much sense.

> I would have hoped that, when we go from active=false to active=true, video encoders would start with a key frame.
> Maybe this is something we could agree on.

Unfortunately active=false/true might have undesirable side-effects, such as actually suspending video stream prior to generating a key frame. Idea is to be able to generate a key frame on a continuous stream. Let me reiterate the scenario, update send bitrate on an already active stream, and request KF to be generated with new bitrate constraint being effective.

2021-03-23 11:26 UTC, youennf commented
> actually suspending video stream prior to generating a key frame
The sender could probably stop sending during one event loop, so the suspension might not be that big a deal in practice.
This would need experimentation.
Also, generating key frame is probably not something that should happen often.

2021-03-23 11:31 UTC, solmaks commented
@youennf , I am not sure how experimentation can help. Observing some behavior in current implementation does not mean it will not change or break in subsequent version. Unless of course we explicitly want to update specification, demanding for active=true/false toggle in a single even loop should not result in stream getting suspended (which I hope we are not willing to do).

2021-03-23 11:34 UTC, solmaks commented
> Also, generating key frame is probably not something that should happen often.

API needs to be robust and produce defined behavior regardless of the frequency it is called. Be it once per minute or once per second. My scenario does not require sub-second processing. However, 1s+ is something that is pretty much required.

2021-03-25 12:41 UTC, youennf commented
I quickly looked at active usage in WebRTC backend. It seems it currently triggers recreation of the whole encoder, so it probably triggers keyframe (good for a short term fix), but for all simulcasted encoders (not great...).

2021-03-25 12:43 UTC, youennf commented
@solmaks, I filed https://github.com/w3c/webrtc-extensions/issues/72 to keep track of this issue given this thread is related to a PR.

2021-03-31 21:33 UTC, solmaks commented
@youennf , @alvestrand , any recommendation on how we can proceed with the proposed extension?

2021-04-01 09:25 UTC, youennf commented
https://github.com/w3c/webrtc-extensions/issues/72 is probably the natural place to continue the discussion.
I think we would need to build a proposal and present it at next WebRTC interim.
Would you be able to carry that forward?
A look at how it could be implemented in browsers in the simulcast case would also be valuable.

2021-04-04 12:55 UTC, fippo commented
> In the case of simulcast, you would like to trigger a key frame for one encoding but not the others.

No. Simulcast is (at least in chrome) not able to do keyframes for individual layers, see https://bugs.chromium.org/p/webrtc/issues/detail?id=10107

2021-04-07 07:50 UTC, solmaks commented
@fippo, I think it is OK to have an API enabling the flexibility to control individual layers, and individual user agents to choose not to do this optimization.

2021-04-07 08:38 UTC, youennf commented
> I think it is OK to have an API enabling the flexibility to control individual layers, and individual user agents to choose not to do this optimization.

That would be sad if different browsers have different behaviours for this API.
This seems like a good topic for next interim.

2021-04-08 04:05 UTC, aboba requested changes
I'd suggest adding an optional argument to specify the streams on which a refresh point should be generated. Inclusion of streams would be interpretted the same as reception of an FIR (which can specify multiple SSRCs).  Since RIDs are exposed and SSRCs may not be, it seems like the best way to accomplish this would be by providing an optional argument containing a sequence of RIDs.  If the optional argument is not provided, then it would apply to all streams sent by the `RTCRtpSender`.

2021-04-08 09:44 UTC, solmaks commented
Good idea, @aboba . This seems to be a better place for it, as opposed to having it on top of encoding configuration.

2022-02-02 18:40 UTC, aboba commented
Closed due to merger of [PR 125](https://github.com/w3c/webrtc-encoded-transform/pull/125).

2022-02-02 18:40 UTC, closed without merging